### sign up
POST http://localhost:8000/api/signup HTTP/1.1
Content-Type: application/json

{   "email": "123@gmail.com",
    "password": "12345678",
    "username" : "test1"
}

### get all users
GET http://localhost:8000/users/getusers HTTP/1.1

### check logined
GET http://localhost:8000/users/logined HTTP/1.1

### sign in
POST http://localhost:8000/api/signin HTTP/1.1
Content-Type: application/json

{   "email": "123",
    "password": "123"
}

### get one id by cvid
GET http://localhost:8000/api/cv/6267c4c221bd94c1f2328c06 HTTP/1.1

### get all cv for developer
GET http://localhost:8000/api/cv HTTP/1.1

### log out
GET  http://localhost:8000/api/signout HTTP/1.1


### get all sessions
GET http://localhost:8000/users/getsession HTTP/1.1

### get all cv
GET http://localhost:8000/api/cv/ HTTP/1.1

### get one id by cvid
GET http://localhost:8000/api/cv/6267c4c221bd94c1f2328c06 HTTP/1.1

### add 1 CV 
POST http://localhost:8000/api/cv HTTP/1.1
Content-Type: application/json

{
    "resumeName": "civizen4",
    "imgUrl": 
    "https://firebasestorage.googleapis.com/v0/b/civipro-4d091.appspot.com/o/templates%2FCastform.png?alt=media&token=c1b11a52-0d3d-4c1a-be97-08415fa49727",
    "demo": true,
    "metadata": {
        "ownerId": "6257d971b921d0153805a5cd", 
        "createdAt": 1629429322.058818,
        "updatedAt": 1630382763.8490574
  }
}

### Update 1 Cv
PUT  http://localhost:8000/api/cv/6267c4c221bd94c1f2328c06 HTTP/1.1
Content-Type: application/json

{
    "resumeName": "civizen4",
    "imgUrl": 
    "https://firebasestorage.googleapis.com/v0/b/civipro-4d091.appspot.com/o/templates%2FCastform.png?alt=media&token=c1b11a52-0d3d-4c1a-be97-08415fa49727",
    "demo": true,
    "metadata": {
        "ownerId": "6257d971b921d0153805a5cd", 
        "createdAt": 1629429322.058818,
        "updatedAt": 1630382763.8490574
  }
}

### get all users
GET http://localhost:8000/users/getusers HTTP/1.1

###
DELETE http://localhost:8000/api/cv/6267c59cfd3b7aa81414cd43 HTTP/1.1
Content-Type: application/json

{
    "userId": "6257d971b921d0153805a5cd"
}

### google log in
GET http://localhost:8000/api/google HTTP/1.1


### 
POST http://localhost:8000/email/sendmail HTTP/1.1
Content-Type: application/json

{
    "to": "dsitweed@gmail.com",
    "subject": "Gmail xác nhận của CVZen",
    "body": "Hãy nhập mã xác nhận: 123456 để xác thực email."
}